---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    url: https://10.1.1.6:9443/mutate-webapp-my-domain-v1-guestbook # This allows for local iteration as otherwise it uses k8s service
    # service:
    #   name: webhook-service
    #   namespace: system
    #   path: /mutate-webapp-my-domain-v1-guestbook
  failurePolicy: Fail
  name: mguestbook-v1.kb.io
  rules:
  - apiGroups:
    - webapp.my.domain
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - guestbooks
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    url: https://10.1.1.6:9443/validate-webapp-my-domain-v1-guestbook # This allows for local iteration as otherwise it uses k8s service
    # service:
    #   name: webhook-service
    #   namespace: system
    #   path: /validate-webapp-my-domain-v1-guestbook
  failurePolicy: Fail
  name: vguestbook-v1.kb.io
  rules:
  - apiGroups:
    - webapp.my.domain
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - guestbooks
  sideEffects: None
